class Game
  #setting getter and setters for the game class
  attr_accessor :players, :player, :turn, :question

  def initialize(player1, player2, question)
    #@players takes form an array which we can use to iteration later when determining the winner
    #@player is the player who is in turn of play
    #@turn takes in the name of the player who is in turn of play
    #@question is the question object generated by the question class
    @players = [player1, player2]
    @player = player1
    @turn = player1.name
    @question = question
  end

  def run_game
    # while loop will continue the game and change the turn respectively until we have a player runs out of life
    while !self.players.find {|player| player.life == 0}
      self.game_procedure
      self.change_turn
    end

    winner = self.players.find {|player| player.life != 0}
    puts "#{winner.name} wins with a score of #{winner.life}/3"
    puts "----- GAME OVER -----"
    puts "Good bye!"
  end

  private
  # setting the following functions private because they do not have anything to do besides invoked by the run_game method. Also, I don't want people to interact with these code directly. 

  # change_turn method changes not only the @turn, but also the @player in turn of play, so that the player.lose_life method can work properly
  def change_turn
    if self.turn == self.players[0].name
      self.turn= self.players[1].name
      self.player= self.players[1]
    else
      self.turn= self.players[0].name
      self.player= self.players[0]
    end
  end

  # game logic here
  def game_procedure
    puts "#{self.turn}: #{self.question.ask_question}"
    print "> "
    
    user_input = $stdin.gets.chomp.to_i
    
    if user_input == self.question.answer
      puts "#{self.turn}: YES! You are correct."
    else
      puts "#{self.turn}: Seriously? No!"
      self.player.lose_life 
    end
    
    # after each turn of valuation, check if no player is ran out of life and move on to the new turn.
    if !self.players.find {|player| player.life == 0}
      puts "#{self.players[0].name}: #{self.players[0].life}/3 vs #{self.players[1].name}: #{self.players[1].life}/3"
      puts "----- NEW TURN -----"
    end
  end
end  